spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-admin


server:
  port: 12000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/